#!/usr/bin/env python3
"""
build_central_bank_json.py

Runs every bank scraper (fomc_scraper, ecb_scraper, boe_scraper,
boc_scraper, rba_scraper, boj_scraper) for the current year and next
year, and regenerates sources/central_bank_dates.json directly from what
each official page actually says right now -- no manual transcription,
no third-party sources.

Run:
    python3 build_central_bank_json.py
Overwrites:
    ../sources/central_bank_dates.json
"""

import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from fomc_scraper import get_fomc_dates
from ecb_scraper import get_ecb_dates
from boe_scraper import get_boe_dates
from boc_scraper import get_boc_dates
from rba_scraper import get_rba_dates
from boj_scraper import get_boj_dates

OUTPUT_FILE = Path(__file__).parent.parent / "sources" / "central_bank_dates.json"

SOURCES = {
    "USD_FOMC": "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    "EUR_ECB": "https://www.ecb.europa.eu/press/calendars/mgcgc/html/index.en.html",
    "GBP_BOE": "https://www.bankofengland.co.uk/monetary-policy/upcoming-mpc-dates",
    "CAD_BOC": "https://www.bankofcanada.ca/press/upcoming-events/",
    "AUD_RBA": "https://www.rba.gov.au/schedules-events/",
    "JPY_BOJ": "https://www.boj.or.jp/en/mopo/mpmsche_minu/index.htm",
}

SCRAPERS = {
    "FOMC": get_fomc_dates,
    "ECB": get_ecb_dates,
    "BOE": get_boe_dates,
    "BOC": get_boc_dates,
    "RBA": get_rba_dates,
    "BOJ": get_boj_dates,
}

PLACEHOLDER_ENTRIES = []  # all six banks now have scrapers -- no placeholders needed


def load_previous_events() -> dict:
    """Loads the existing JSON (if any) so failed scrapers can fall back to
    last-known-good data instead of silently losing that bank's entries."""
    if not OUTPUT_FILE.exists():
        return {}
    try:
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}

    by_bank = {}
    for ev in data.get("events", []):
        by_bank.setdefault(ev.get("bank"), []).append(ev)
    return by_bank


def main():
    today = date.today()
    years_to_fetch = [today.year, today.year + 1]

    previous_by_bank = load_previous_events()

    all_events = []
    errors = []

    for bank_name, scraper_func in SCRAPERS.items():
        bank_events = []
        bank_failed = False
        for year in years_to_fetch:
            try:
                events = scraper_func(year)
                print(f"{bank_name} {year}: {len(events)} meetings found")
                bank_events.extend(events)
            except Exception as e:
                msg = f"{bank_name} {year}: FAILED to scrape -- {e}"
                print(f"  [!] {msg}", file=sys.stderr)
                errors.append(msg)
                bank_failed = True

        if bank_failed and not bank_events:
            # total failure for this bank -- fall back to whatever was in
            # the previous JSON rather than losing the bank's data outright
            fallback = previous_by_bank.get(bank_name, [])
            if fallback:
                print(
                    f"  [!] {bank_name}: using {len(fallback)} entries from previous "
                    f"run as fallback (STALE -- scraper failed this run)",
                    file=sys.stderr,
                )
                for ev in fallback:
                    ev = dict(ev)
                    ev["note"] = (ev.get("note", "") + " [STALE: scraper failed on last run]").strip()
                bank_events = fallback

        # only keep meetings that haven't already happened
        bank_events = [e for e in bank_events if e.get("date", "") >= today.isoformat()]
        all_events.extend(bank_events)

    all_events.sort(key=lambda e: e["date"])
    all_events.extend(PLACEHOLDER_ENTRIES)

    output = {
        "_readme": [
            "This file is auto-generated by scrapers/build_central_bank_json.py,",
            "which fetches each bank's OFFICIAL page directly and parses the dates",
            "from the live page text. It is NOT manually transcribed.",
            "",
            "DO NOT hand-edit any entries below -- they will be overwritten the",
            "next time the scraper runs. To fix a wrong date, fix the relevant",
            "scraper (in scrapers/), not this file.",
            "",
            "All six banks (FOMC, ECB, BOE, BOC, RBA, BOJ) now have working",
            "scrapers. If a scraper fails on a given run, that bank's entries",
            "fall back to their last-known-good data (marked STALE in the note)",
            "rather than disappearing -- check scraper_errors below for failures.",
            "",
            f"Last generated: {today.isoformat()}",
        ],
        "last_verified": today.isoformat(),
        "sources": SOURCES,
        "scraper_errors": errors,
        "events": all_events,
    }

    OUTPUT_FILE.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"\nWrote {len(all_events)} events ({len(all_events) - len(PLACEHOLDER_ENTRIES)} confirmed + {len(PLACEHOLDER_ENTRIES)} placeholders) to {OUTPUT_FILE}")

    if errors:
        print(f"\n{len(errors)} scraper call(s) failed -- see above. Banks with a total "
              f"failure fell back to their previous data (marked STALE); banks where "
              f"only one of the two years failed still got partial fresh data.", file=sys.stderr)


if __name__ == "__main__":
    main()
