#!/usr/bin/env python3
"""
build_data_releases_json.py

Runs the data-release scrapers (bls_scraper, bea_scraper, dol_scraper) for
the current year and next year, and regenerates sources/data_releases.json
directly from each agency's official source -- no manual transcription.

INTENTIONALLY SEPARATE from build_central_bank_json.py: these are
scheduled data publications (CPI, PPI, PCE, Jobless Claims), not central
bank rate decisions. Keeping them in a different file/pipeline avoids
conflating two different kinds of events that need different
title/impact handling downstream.

Which specific BLS/BEA releases get included is controlled by
watched_releases.json -- edit that file to add/remove releases. DOL is
NOT filtered this way since it only has one release type (weekly
jobless claims) -- see dol_scraper.py's docstring for how DOL differs
structurally from BLS/BEA (recurring weekly rule + holiday exceptions,
not a fixed list of dated events).

Run:
    python3 build_data_releases_json.py
Overwrites:
    ../sources/data_releases.json
"""

import json
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from bls_scraper import get_bls_dates
from bea_scraper import get_bea_dates
from dol_scraper import get_dol_dates

OUTPUT_FILE = Path(__file__).parent.parent / "sources" / "data_releases.json"

# How many days in the past to still include in the output. 0 = only
# today and future events (the original behavior). Set higher to keep
# recently-passed releases visible in the calendar for reference.
LOOKBACK_DAYS = 90

SOURCES = {
    "BLS": "https://www.bls.gov/schedule/news_release/bls.ics",
    "BEA": "https://www.bea.gov/news/schedule/ics/online-calendar-subscription.ics",
    "DOL": "https://oui.doleta.gov/unemploy/claims_arch.asp",
}

SCRAPERS = {
    "BLS": get_bls_dates,
    "BEA": get_bea_dates,
    "DOL": get_dol_dates,
}


def load_previous_events() -> dict:
    if not OUTPUT_FILE.exists():
        return {}
    try:
        with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return {}

    by_agency = {}
    for ev in data.get("events", []):
        by_agency.setdefault(ev.get("bank"), []).append(ev)
    return by_agency


def main():
    today = date.today()
    cutoff_date = (today - timedelta(days=LOOKBACK_DAYS)).isoformat()
    cutoff_year = (today - timedelta(days=LOOKBACK_DAYS)).year
    years_to_fetch = sorted({cutoff_year, today.year, today.year + 1})

    previous_by_agency = load_previous_events()

    all_events = []
    errors = []

    for agency_name, scraper_func in SCRAPERS.items():
        agency_events = []
        agency_failed = False
        for year in years_to_fetch:
            try:
                events = scraper_func(year)
                print(f"{agency_name} {year}: {len(events)} watched releases found")
                agency_events.extend(events)
            except Exception as e:
                msg = f"{agency_name} {year}: FAILED to scrape -- {e}"
                print(f"  [!] {msg}", file=sys.stderr)
                errors.append(msg)
                agency_failed = True

        if agency_failed and not agency_events:
            fallback = previous_by_agency.get(agency_name, [])
            if fallback:
                print(
                    f"  [!] {agency_name}: using {len(fallback)} entries from previous "
                    f"run as fallback (STALE -- scraper failed this run)",
                    file=sys.stderr,
                )
                for ev in fallback:
                    ev = dict(ev)
                    ev["note"] = (ev.get("note", "") + " [STALE: scraper failed on last run]").strip()
                agency_events = fallback

        agency_events = [e for e in agency_events if e.get("date", "") >= cutoff_date]
        all_events.extend(agency_events)

    all_events.sort(key=lambda e: e["date"])

    output = {
        "_readme": [
            "This file is auto-generated by scrapers/build_data_releases_json.py,",
            "which fetches each agency's OFFICIAL ICS feed directly and filters to",
            "the releases listed in watched_releases.json. It is NOT manually",
            "transcribed.",
            "",
            "DO NOT hand-edit the events below -- they will be overwritten the next",
            "time the scraper runs. To change WHICH releases are included, edit",
            "watched_releases.json. To fix a parsing bug, fix the relevant scraper",
            "(bls_scraper.py / bea_scraper.py), not this file.",
            "",
            f"Last generated: {today.isoformat()}",
        ],
        "last_verified": today.isoformat(),
        "sources": SOURCES,
        "scraper_errors": errors,
        "events": all_events,
    }

    OUTPUT_FILE.write_text(json.dumps(output, indent=2), encoding="utf-8")
    print(f"\nWrote {len(all_events)} events to {OUTPUT_FILE}")

    if errors:
        print(f"\n{len(errors)} scraper call(s) failed -- see above.", file=sys.stderr)


if __name__ == "__main__":
    main()
